db:
  options:
    url: db-url
    driver: db-driver
    fetchsize: db-fetchsize
    batchsize: db-batchsize
    user: db-user
    password: db-password
  resources:
    test:
      path: ( SELECT ID, NAME FROM SPARK_YZ.TEST_YZ ) data

hdfs:
  host: localhost
  port: 9000
  resources:
    test:
      path: output.csv
      schema: id INT, name STRING
      options:
        header: true

s3-conf:
  key: key-conf
  secret: secret-conf
  bucket: bucket-conf
  endpoint: endpoint-conf
  resources:
    test:
      path: yazabara/input.csv
      schema: id INT, name STRING
      options:
        header: true

file:
  resources:
    test:
      path: src/main/resources/spark-resources/input.csv
      schema: id INT, name STRING
      options:
        header: true