logging:
  level:
    odh.tool: DEBUG
    org.springframework: INFO
  file: spark-hadoop/app.log

hdfs:
  host: localhost
  port: 9000

s3-conf:
  key: key-conf
  secret: secret-conf
  bucket: bucket-conf
  endpoint: endpoint-conf